<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ServiciosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('servicios')->insert([
            [
                'tipo_servicio' => 'CP',
                'descripcion' => 'Control de plagas en jardín',
                'fecha_servicio' => '2025-01-15',
                'hora_servicio' => '08:00:00',
                'duracion' => 2,
                'presupuesto' => 150.00,
                'metodo_pago' => 'EF',
                'estado' => 'P',
                'id_parcela' => 1,
                'ip_alta' => '192.168.1.1',
                'created_at' => now(),
            ],
            [
                'tipo_servicio' => 'CM',
                'descripcion' => 'Control de maleza en patio',
                'fecha_servicio' => '2025-02-10',
                'hora_servicio' => '09:00:00',
                'duracion' => 3,
                'presupuesto' => 120.50,
                'metodo_pago' => 'TA',
                'estado' => 'N',
                'id_parcela' => 2,
                'ip_alta' => '192.168.1.2',
                'created_at' => now(),
            ],
            [
                'tipo_servicio' => 'SC',
                'descripcion' => 'Sembrado en cazolejas',
                'fecha_servicio' => '2025-03-05',
                'hora_servicio' => '07:00:00',
                'duracion' => 4,
                'presupuesto' => 200.00,
                'metodo_pago' => 'TR',
                'estado' => 'P',
                'id_parcela' => 3,
                'ip_alta' => '192.168.1.3',
                'created_at' => now(),
            ],
            [
                'tipo_servicio' => 'SS',
                'descripcion' => 'Sembrado por surcos en campo',
                'fecha_servicio' => '2025-04-20',
                'hora_servicio' => '10:00:00',
                'duracion' => 5,
                'presupuesto' => 175.75,
                'metodo_pago' => 'EF',
                'estado' => 'N',
                'id_parcela' => 4,
                'ip_alta' => '192.168.1.4',
                'created_at' => now(),
            ],
            [
                'tipo_servicio' => 'CP',
                'descripcion' => 'Control de plagas en almacén',
                'fecha_servicio' => '2025-05-12',
                'hora_servicio' => '11:00:00',
                'duracion' => 2,
                'presupuesto' => 220.00,
                'metodo_pago' => 'TR',
                'estado' => 'P',
                'id_parcela' => 5,
                'ip_alta' => '192.168.1.5',
                'created_at' => now(),
            ],
            [
                'tipo_servicio' => 'CM',
                'descripcion' => 'Eliminación de maleza en camino',
                'fecha_servicio' => '2025-06-08',
                'hora_servicio' => '07:30:00',
                'duracion' => 3,
                'presupuesto' => 130.00,
                'metodo_pago' => 'EF',
                'estado' => 'N',
                'id_parcela' => 6,
                'ip_alta' => '192.168.1.6',
                'created_at' => now(),
            ],
            [
                'tipo_servicio' => 'SC',
                'descripcion' => 'Sembrado de pasto',
                'fecha_servicio' => '2025-07-22',
                'hora_servicio' => '09:00:00',
                'duracion' => 4,
                'presupuesto' => 195.00,
                'metodo_pago' => 'TA',
                'estado' => 'P',
                'id_parcela' => 7,
                'ip_alta' => '192.168.1.7',
                'created_at' => now(),
            ],
            [
                'tipo_servicio' => 'SS',
                'descripcion' => 'Sembrado de flores en parque',
                'fecha_servicio' => '2025-08-14',
                'hora_servicio' => '12:00:00',
                'duracion' => 5,
                'presupuesto' => 180.00,
                'metodo_pago' => 'TR',
                'estado' => 'N',
                'id_parcela' => 8,
                'ip_alta' => '192.168.1.8',
                'created_at' => now(),
            ],
            [
                'tipo_servicio' => 'CP',
                'descripcion' => 'Control de plagas en viñedo',
                'fecha_servicio' => '2025-09-10',
                'hora_servicio' => '08:00:00',
                'duracion' => 2,
                'presupuesto' => 210.00,
                'metodo_pago' => 'EF',
                'estado' => 'P',
                'id_parcela' => 9,
                'ip_alta' => '192.168.1.9',
                'created_at' => now(),
            ],
            [
                'tipo_servicio' => 'CM',
                'descripcion' => 'Limpieza de maleza en huerto',
                'fecha_servicio' => '2025-10-18',
                'hora_servicio' => '09:00:00',
                'duracion' => 3,
                'presupuesto' => 140.50,
                'metodo_pago' => 'TA',
                'estado' => 'N',
                'id_parcela' => 10,
                'ip_alta' => '192.168.1.10',
                'created_at' => now(),
            ],
            [
                'tipo_servicio' => 'SC',
                'descripcion' => 'Siembra de trigo',
                'fecha_servicio' => '2025-11-25',
                'hora_servicio' => '07:30:00',
                'duracion' => 4,
                'presupuesto' => 250.00,
                'metodo_pago' => 'TR',
                'estado' => 'P',
                'id_parcela' => 11,
                'ip_alta' => '192.168.1.11',
                'created_at' => now(),
            ],
            [
                'tipo_servicio' => 'SS',
                'descripcion' => 'Siembra de maíz en surcos',
                'fecha_servicio' => '2025-12-05',
                'hora_servicio' => '10:00:00',
                'duracion' => 5,
                'presupuesto' => 230.75,
                'metodo_pago' => 'EF',
                'estado' => 'N',
                'id_parcela' => 12,
                'ip_alta' => '192.168.1.12',
                'created_at' => now(),
            ],
        ]);
    }
}
