<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FitosanitariosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('fitosanitarios')->insert([
            [
                'nombre' => 'Confidor 20 LS',
                'marca' => 'Bayer CropScience',
                'numero_registro' => '20-30-00001-HA',
                'tipo' => 'IN',
                'estado' => 'VV',
                'descripcion' => 'Insecticida sistémico para el control de diversas plagas.',
                'entidad_vendedora' => 'Fitosanitarios Lanzarote S.C.',
                'materia_activa' => 'Imidacloprid',
                'cantidad_materia_activa' => 0.2,
                'dosis_maxima' => 0.5,
                'plazo_seguridad' => 21,
                'observaciones' => 'Aplicar en horas de baja insolación para evitar evaporación.',
                'ip_alta' => '192.168.1.104',
                'ip_ult_mod' => '192.168.1.104',
                'created_at' => now(),
            ],
            [
                'nombre' => 'Roundup UltraPlus',
                'marca' => 'Monsanto Agricultura España',
                'numero_registro' => '20-10-00002-HA',
                'tipo' => 'HE',
                'estado' => 'VV',
                'descripcion' => 'Herbicida no selectivo para el control de malezas.',
                'entidad_vendedora' => 'Servimor Lanzarote',
                'materia_activa' => 'Glifosato',
                'cantidad_materia_activa' => 1.8,
                'dosis_maxima' => 4.0,
                'plazo_seguridad' => 7,
                'observaciones' => 'Evitar el contacto con cultivos deseados.',
                'ip_alta' => '192.168.1.104',
                'ip_ult_mod' => '192.168.1.104',
                'created_at' => now(),
            ],
            [
                'nombre' => 'Aliette WG',
                'marca' => 'Bayer CropScience',
                'numero_registro' => '20-40-00003-HA',
                'tipo' => 'FU',
                'estado' => 'PV',
                'descripcion' => 'Fungicida sistémico para el control de enfermedades fúngicas.',
                'entidad_vendedora' => 'Tahiche Garden Lanzarote',
                'materia_activa' => 'Fosetil-Al',
                'cantidad_materia_activa' => 1.15,
                'dosis_maxima' => 3.0,
                'plazo_seguridad' => 15,
                'observaciones' => 'Recomendado para cultivos de vid y cítricos.',
                'ip_alta' => '192.168.1.104',
                'ip_ult_mod' => '192.168.1.104',
                'created_at' => now(),
            ],
            [
                'nombre' => 'Decis Protech',
                'marca' => 'Bayer CropScience',
                'numero_registro' => '20-30-00004-HA',
                'tipo' => 'IN',
                'estado' => 'VV',
                'descripcion' => 'Insecticida piretroide de amplio espectro.',
                'entidad_vendedora' => 'Fitosanitarios Lanzarote S.C.',
                'materia_activa' => 'Deltametrina',
                'cantidad_materia_activa' => 0.18,
                'dosis_maxima' => 0.3,
                'plazo_seguridad' => 7,
                'observaciones' => 'Eficaz contra lepidópteros y otros insectos.',
                'ip_alta' => '192.168.1.104',
                'ip_ult_mod' => '192.168.1.104',
                'created_at' => now(),
            ],
            [
                'nombre' => 'Folicur WG',
                'marca' => 'Bayer CropScience',
                'numero_registro' => '20-40-00005-HA',
                'tipo' => 'FU',
                'estado' => 'PV',
                'descripcion' => 'Fungicida sistémico para el control de oídios y royas.',
                'entidad_vendedora' => 'Servimor Lanzarote',
                'materia_activa' => 'Tebuconazol',
                'cantidad_materia_activa' => 0.25,
                'dosis_maxima' => 1.0,
                'plazo_seguridad' => 14,
                'observaciones' => 'Aplicar preventivamente para mejores resultados.',
                'ip_alta' => '192.168.1.104',
                'ip_ult_mod' => '192.168.1.104',
                'created_at' => now(),
            ],
            [
                'nombre' => 'Karate Zeon',
                'marca' => 'Syngenta Agro S.A.',
                'numero_registro' => '20-30-00006-HA',
                'tipo' => 'IN',
                'estado' => 'VV',
                'descripcion' => 'Insecticida piretroide microencapsulado.',
                'entidad_vendedora' => 'Fitosanitarios Lanzarote S.C.',
                'materia_activa' => 'Lambda-cihalotrina',
                'cantidad_materia_activa' => 0.09,
                'dosis_maxima' => 0.2,
                'plazo_seguridad' => 14,
                'observaciones' => 'Eficaz contra insectos masticadores y chupadores.',
                'ip_alta' => '192.168.1.104',
                'ip_ult_mod' => '192.168.1.104',
                'created_at' => now(),
            ],
            [
                'nombre' => 'Ridomil Gold',
                'marca' => 'Syngenta Agro S.A.',
                'numero_registro' => '20-40-00007-HA',
                'tipo' => 'FU',
                'estado' => 'PV',
                'descripcion' => 'Fungicida sistémico para el control de mildiu.',
                'entidad_vendedora' => 'Tahiche Garden Lanzarote',
                'materia_activa' => 'Metalaxil-M',
                'cantidad_materia_activa' => 2.0,
                'dosis_maxima' => 2.5,
                'plazo_seguridad' => 21,
                'observaciones' => 'No aplicar en épocas de alta humedad.',
                'ip_alta' => '192.168.1.104',
                'ip_ult_mod' => '192.168.1.104',
                'created_at' => now(),
            ],
            [
                'nombre' => 'Maton',
                'marca' => 'Probelte S.A.',
                'numero_registro' => '20-10-00008-HA',
                'tipo' => 'HE',
                'estado' => 'VV',
                'descripcion' => 'Herbicida selectivo para cereales.',
                'entidad_vendedora' => 'Servimor Lanzarote',
                'materia_activa' => 'MCPA',
                'cantidad_materia_activa' => 0.5,
                'dosis_maxima' => 1.5,
                'plazo_seguridad' => 30,
                'observaciones' => 'Evitar aplicar en cultivos de hoja ancha.',
                'ip_alta' => '192.168.1.104',
                'ip_ult_mod' => '192.168.1.104',
                'created_at' => now(),
            ],
            [
                'nombre' => 'Ortiva',
                'marca' => 'Syngenta Agro S.A.',
                'numero_registro' => '20-40-00009-HA',
                'tipo' => 'FU',
                'estado' => 'PP',
                'descripcion' => 'Fungicida de amplio espectro para hortícolas.',
                'entidad_vendedora' => 'Tahiche Garden Lanzarote',
                'materia_activa' => 'Azoxistrobina',
                'cantidad_materia_activa' => 0.25,
                'dosis_maxima' => 1.0,
                'plazo_seguridad' => 3,
                'observaciones' => 'Recomendado para cultivos de tomate y pimiento.',
                'ip_alta' => '192.168.1.104',
                'ip_ult_mod' => '192.168.1.104',
                'created_at' => now(),
            ],
            [
                'nombre' => 'Pirimor G',
                'marca' => 'Syngenta Agro S.A.',
                'numero_registro' => '20-30-00010-HA',
                'tipo' => 'IN',
                'estado' => 'VV',
                'descripcion' => 'Insecticida específico para pulgones.',
                'entidad_vendedora' => 'Fitosanitarios Lanzarote S.C.',
                'materia_activa' => 'Pirimicarb',
                'cantidad_materia_activa' => 0.2,
                'dosis_maxima' => 0.5,
                'plazo_seguridad' => 7,
                'observaciones' => 'No afecta a insectos beneficiosos.',
                'ip_alta' => '192.168.1.104',
                'ip_ult_mod' => '192.168.1.104',
                'created_at' => now(),
            ]
        ]);
    }
}
